AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'db/**/*'

Rails:
  Enabled: true

# Accept single-line methods with no body
SingleLineMethods:
  AllowIfMethodIsEmpty: true

# Top-level documentation of classes and modules are needless
Documentation:
  Enabled: false

# Allow to chain of block after another block that spans multiple lines
MultilineBlockChain:
  Enabled: false

# Allow `->` literal for multi line blocks
Lambda:
  Enabled: false

# Both nested and compact are okay
ClassAndModuleChildren:
  Enabled: false

# Specifying param names is unnecessary
Style/SingleLineBlockParams:
  Enabled: false

# Allow using `{...}` for anytime
Style/BlockDelimiters:
  Enabled: false

# Prefer Kernel#sprintf
FormatString:
  EnforcedStyle: sprintf

# Maximum line length
LineLength:
  Max: 100

# Whatever we should use "postfix if/unless"
IfUnlessModifier:
  MaxLineLength: 100

# Maximum method length
MethodLength:
  Max: 20

# Tuned to MethodLength
Metrics/AbcSize:
  Max: 30

# Prefer double_quotes strings unless your string literal contains escape chars
StringLiterals:
  EnforcedStyle: single_quotes

# Put a comma after the last item of a multiline array or hash
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

AsciiComments:
  Enabled: false

SignalException:
    EnforcedStyle: only_raise
